### ISSUE TITLE
As the amount of data increases, the difference between the simulated values and the test values becomes larger, but the proportion remains unchanged.

### ISSUE THREAD

**Issue by shao-ssq** [bytedance/videx#20]
### Environment Setup

kangrongme/videx:0.0.3
mysql 5.7

### Observed vs Expected Behavior

As the amount of data increases, the difference between the simulated values and the test values grows, but it is still usable from a practical standpoint.

![Image](https://github.com/user-attachments/assets/d9f6cc3a-af73-4e65-b4f5-3850872894d2)

![Image](https://github.com/user-attachments/assets/aed688ce-fa60-427d-8322-fda876e559b7)

SQL
```sql
CREATE TABLE user_orders (
    id BIGINT PRIMARY KEY,
    user_id BIGINT,
    status INT, 
    order_amount DECIMAL(10,2),
    create_time DATETIME,
    INDEX idx_status (status) 
);

DELIMITER $$
 
CREATE PROCEDURE insert_user_orders()
BEGIN
    DECLARE i INT DEFAULT 1;  
    WHILE i <= 10000 DO
        INSERT INTO user_orders (id, user_id, status, order_amount, create_time)
        VALUES (
            i,
            FLOOR(RAND() * 10000),
            FLOOR(RAND() * 3),
            ROUND(RAND() * 1000, 2),
            NOW() - INTERVAL FLOOR(RAND() * 365) DAY
        );
        SET i = i + 1;
    END WHILE;
END $$
 
DELIMITER ;
CALL insert_user_orders();
```

**Comment by kr11** [comment]
@shao-ssq Thanks for your reporting! We will start to handle it in the next two days.

**Comment by Spock12138** [comment]
@shao-ssq Hi, I have created a test_users database, which contains a user_orders table. What is your EXPLAIN statement example?

**Comment by shao-ssq** [comment]
It looks fine under 8.0, but I tested the results under 5.7. I might have written it wrong — it’s actually 1,000,000.  It takes about 200 seconds for every 100,000 inserts.  If possible, could you help test it under version 5.7?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SHAOQI~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SHAOQI~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


  | 5w | 10w | 20w | 30w | 40w | 50w | 60w | 70w | 80w | 90w | 100w
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
测试环境 | 767 | 11044.6 | 21982.6 | 32920.6 | 42726.8 | 54398.2 | 65344.2 | 76643.2 | 87383.8 | 98134.6 | 109056.6
模拟环境 | 762.2 | 7695 | 15342.2 | 22945.2 | 29719.6 | 37747.4 | 45322.2 | 53355 | 60753.2 | 68183.4 | 75786.2



</body>

</html>

**Comment by Spock12138** [comment]
It is remarkable, and it is quick to insert 10 W pieces of data. It took me approximately 10 minutes to insert 10 W data into Windows. As illustrated in Fig
![Image](https://github.com/user-attachments/assets/8a0cb12d-c623-4669-a9d3-80f5205f82c0)

The following action commands are executed.
```
CREATE PROCEDURE insert_user_orders_10w()
BEGIN
    DECLARE i INT DEFAULT 1;  
    WHILE i <= 100000 DO
        INSERT INTO user_orders (id, user_id, status, order_amount, create_time)
        VALUES (
            i,
            FLOOR(RAND() * 10000),
            FLOOR(RAND() * 3),
            ROUND(RAND() * 1000, 2),
            NOW() - INTERVAL FLOOR(RAND() * 365) DAY
        );
        SET i = i + 1;
    END WHILE;
END $$
```

Then may I ask how you obtain the comparison of InnoDB and Videx with different data volumes? Is it necessary to delete the Docker images each time and reinstall to avoid the impact of caching?

**Comment by kr11** [comment]
hi @shao-ssq  

thank you @Spock12138 for your valuable discussion.

I try to reproduce VIDEX on 5.7, but haven't found the difference. I will show my scripts and output firstly, and then provide some validation scripts. Please try them.

# My Scripts
Create three tables and insert random data

```sql
CREATE TABLE IF NOT EXISTS user_orders_100k (
    id INT PRIMARY KEY,
    user_id INT,
    status INT,
    order_amount DECIMAL(10,2),
    create_time DATETIME
);
CREATE TABLE IF NOT EXISTS user_orders_200k (
    id INT PRIMARY KEY,
    user_id INT,
    status INT,
    order_amount DECIMAL(10,2),
    create_time DATETIME
);
CREATE TABLE IF NOT EXISTS user_orders_500k (
    id INT PRIMARY KEY,
    user_id INT,
    status INT,
    order_amount DECIMAL(10,2),
    create_time DATETIME
);

DROP PROCEDURE IF EXISTS insert_data_to_table;
DELIMITER $$
CREATE PROCEDURE insert_data_to_table(IN table_name VARCHAR(50), IN start_id INT, IN total_records INT)
BEGIN
    DECLARE i INT DEFAULT 0;
    DECLARE sql_text TEXT;
    
    WHILE i < total_records DO
        SET sql_text = CONCAT('INSERT INTO ', table_name, 
                             ' (id, user_id, status, order_amount, create_time) VALUES (',
                             start_id + i, ', ',
                             FLOOR(RAND() * 10000), ', ',
                             FLOOR(RAND() * 3), ', ',
                             ROUND(RAND() * 1000, 2), ', ',
                             '"', DATE_FORMAT(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 365) DAY), '%Y-%m-%d %H:%i:%s'), '"',
                             ')');
        
        SET @sql = sql_text;
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
        
        SET i = i + 1;
    END WHILE;
END $$
DELIMITER ;

CALL insert_data_to_table('user_orders_100k', 1, 100000);
CALL insert_data_to_table('user_orders_200k', 1, 200000);
CALL insert_data_to_table('user_orders_500k', 1, 500000);
```

create videx docker, note the md5:

```sh
docker run -d -p 13308:13308 -p 5001:5001 --name videx kangrongme/videx:0.0.3
1e95c0c41ece3ff28d099af45e7958c4aed18e9c5bd55b7a77562e5281a85062
```

build env, collect data and set environment for mysql 5.7:

```sh
cd src/sub_platforms/sql_opt/videx/scripts
python videx_build_env.py --target {target_host}:{port}:test_cost_db:{user}:{pwd} --videx {videx_host}:13308:videx_test_cost_db:videx:password

mysql -h{videx_host} -P13308 -uvidex -ppassword < setup_mysql57_env.sql
```

explain 3 sqls:

```sql
EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_100k WHERE status = 1\G
EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_200k WHERE status = 1\G
EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_500k WHERE status = 1\G
```

![Image](https://github.com/user-attachments/assets/7c70e188-b535-482d-8121-7d13b56d090c)

**Comment by kr11** [comment]
If my scripts are no problem and you still find differences in my steps, can you please run sqls as follows?

```sql
SELECT VERSION();
select * from mysql.server_cost;
select * from mysql.engine_cost;
```


![Image](https://github.com/user-attachments/assets/493985fd-6f44-4e4a-a0f0-0c9c54e53d0d)

**Comment by shao-ssq** [comment]
@kr11 

Thank you for the clarification! I understand the two key differences you pointed out:

1️⃣ Adding data based on an existing table
— You are inserting new data into an already existing table, not just running queries on a freshly created table. This means the data distribution, primary keys, unique keys, etc., can all be affected by the existing data, so the query plan would differ from the case of an “empty table” or a “newly created table.”

2️⃣ Index setup issue
— In my example, I might not have explicitly set up indexes (or the example didn’t emphasize them), which causes the optimizer to perform full table scans. That would naturally lead to similar or identical behaviors in the query results.

**Comment by kr11** [comment]
> [@kr11](https://github.com/kr11)
> 
> Thank you for the clarification! I understand the two key differences you pointed out:
> 
> There are two differences between your reply and my situation. First, I am adding new data based on an existing table. Second, it seems that your table has no indexes set, so all queries are using full table scans — that would naturally produce the same results.您的回复和我的情况有两点不同。首先，我是基于现有表添加新数据。其次，您的表似乎没有设置索引，因此所有查询都使用全表扫描——这自然会产生相同的结果。

@shao-ssq  
Got it. I will try again, use corrected table schema and increase data step by step :)
```
CREATE TABLE user_orders (
    id BIGINT PRIMARY KEY,
    user_id BIGINT,
    status INT, 
    order_amount DECIMAL(10,2),
    create_time DATETIME,
    INDEX idx_status (status) 
);
```

**Comment by Spock12138** [comment]
> hi [@shao-ssq](https://github.com/shao-ssq)
> 
> thank you [@Spock12138](https://github.com/Spock12138) for your valuable discussion.
> 
> I try to reproduce VIDEX on 5.7, but haven't found the difference. I will show my scripts and output firstly, and then provide some validation scripts. Please try them.
> 
> # My Scripts
> Create three tables and insert random data
> 
> CREATE TABLE IF NOT EXISTS user_orders_100k (
>     id INT PRIMARY KEY,
>     user_id INT,
>     status INT,
>     order_amount DECIMAL(10,2),
>     create_time DATETIME
> );
> CREATE TABLE IF NOT EXISTS user_orders_200k (
>     id INT PRIMARY KEY,
>     user_id INT,
>     status INT,
>     order_amount DECIMAL(10,2),
>     create_time DATETIME
> );
> CREATE TABLE IF NOT EXISTS user_orders_500k (
>     id INT PRIMARY KEY,
>     user_id INT,
>     status INT,
>     order_amount DECIMAL(10,2),
>     create_time DATETIME
> );
> 
> DROP PROCEDURE IF EXISTS insert_data_to_table;
> DELIMITER $$
> CREATE PROCEDURE insert_data_to_table(IN table_name VARCHAR(50), IN start_id INT, IN total_records INT)
> BEGIN
>     DECLARE i INT DEFAULT 0;
>     DECLARE sql_text TEXT;
>     
>     WHILE i < total_records DO
>         SET sql_text = CONCAT('INSERT INTO ', table_name, 
>                              ' (id, user_id, status, order_amount, create_time) VALUES (',
>                              start_id + i, ', ',
>                              FLOOR(RAND() * 10000), ', ',
>                              FLOOR(RAND() * 3), ', ',
>                              ROUND(RAND() * 1000, 2), ', ',
>                              '"', DATE_FORMAT(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 365) DAY), '%Y-%m-%d %H:%i:%s'), '"',
>                              ')');
>         
>         SET @sql = sql_text;
>         PREPARE stmt FROM @sql;
>         EXECUTE stmt;
>         DEALLOCATE PREPARE stmt;
>         
>         SET i = i + 1;
>     END WHILE;
> END $$
> DELIMITER ;
> 
> CALL insert_data_to_table('user_orders_100k', 1, 100000);
> CALL insert_data_to_table('user_orders_200k', 1, 200000);
> CALL insert_data_to_table('user_orders_500k', 1, 500000);
> create videx docker, note the md5:
> 
> docker run -d -p 13308:13308 -p 5001:5001 --name videx kangrongme/videx:0.0.3
> 1e95c0c41ece3ff28d099af45e7958c4aed18e9c5bd55b7a77562e5281a85062
> build env, collect data and set environment for mysql 5.7:
> 
> cd src/sub_platforms/sql_opt/videx/scripts
> python videx_build_env.py --target {target_host}:{port}:test_cost_db:{user}:{pwd} --videx {videx_host}:13308:videx_test_cost_db:videx:password
> 
> mysql -h{videx_host} -P13308 -uvidex -ppassword < setup_mysql57_env.sql
> explain 3 sqls:
> 
> EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_100k WHERE status = 1\G
> EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_200k WHERE status = 1\G
> EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_500k WHERE status = 1\G
> ![Image](https://github.com/user-attachments/assets/7c70e188-b535-482d-8121-7d13b56d090c)

@kr11 Hello, in the MySQL 8.0 environment, without testing the index, I attempted to execute your script, during which creating the database took a considerable amount of time, **as shown in the following image:**

![Image](https://github.com/user-attachments/assets/01493142-2f6e-4ac6-bff3-bc694d756001)

**Optimise your build database script with the following code:**
```
DROP PROCEDURE IF EXISTS insert_data_to_table;
DELIMITER $$
CREATE PROCEDURE insert_data_to_table(IN table_name VARCHAR(50), IN start_id INT, IN total_records INT)
BEGIN
    DECLARE i INT DEFAULT 0;
    DECLARE batch_size INT DEFAULT 1000;
    DECLARE sql_text TEXT;
    
    SET @disable_sql = CONCAT('ALTER TABLE ', table_name, ' DISABLE KEYS');
    PREPARE stmt_disable FROM @disable_sql;
    EXECUTE stmt_disable;
    DEALLOCATE PREPARE stmt_disable;
    
    SET autocommit = 0;
    SET unique_checks = 0;
    SET foreign_key_checks = 0;
    
    WHILE i < total_records DO
        START TRANSACTION;
        SET sql_text = CONCAT('INSERT INTO ', table_name, 
                            ' (id, user_id, status, order_amount, create_time) VALUES ');
        REPEAT
            SET sql_text = CONCAT(sql_text, 
                '(', start_id + i, ',',
                FLOOR(RAND() * 10000), ',',
                FLOOR(RAND() * 3), ',',
                ROUND(RAND() * 1000, 2), ',',
                '"', DATE_FORMAT(DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 365) DAY), '%Y-%m-%d %H:%i:%s'), '"),'
            );
            SET i = i + 1;
        UNTIL i % batch_size = 0 OR i >= total_records END REPEAT;
        
        SET @dynamic_sql = CONCAT(TRIM(TRAILING ',' FROM sql_text), ';');
        PREPARE stmt FROM @dynamic_sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
        
        COMMIT;
    END WHILE;
    
    SET @enable_sql = CONCAT('ALTER TABLE ', table_name, ' ENABLE KEYS');
    PREPARE stmt_enable FROM @enable_sql;
    EXECUTE stmt_enable;
    DEALLOCATE PREPARE stmt_enable;
    
    SET autocommit = 1;
    SET unique_checks = 1;
    SET foreign_key_checks = 1;
    
    SET @analyze_sql = CONCAT('ANALYZE TABLE ', table_name);
    PREPARE stmt_analyze FROM @analyze_sql;
    EXECUTE stmt_analyze;
    DEALLOCATE PREPARE stmt_analyze;
END$$
DELIMITER ;
```

**The speed is faster, as shown in the figure below:**

![Image](https://github.com/user-attachments/assets/6c9d0698-0dbc-4d70-8ba3-210c8b923f69)

Finally, the results of the comparison of **innodb** and **videx** are consistent.

![Image](https://github.com/user-attachments/assets/5455291c-610a-4203-93b6-893556975f5a)

**Comment by kr11** [comment]
hi @shao-ssq 

I've pushed a PR #22 to resolve #20 (this PR) and #19 , please kindly test it.

Firstly, pull the recent docker version (kangrongme/videx:0.1.0), and checkout to the branch `kangrong/fix/model_and_meta_cache`.

```sh
docker run -d -p 13308:13308 -p 5001:5001 --name videx kangrongme/videx:0.1.0
```


Create table and insert random data

```sql

drop table if exists user_orders;

CREATE TABLE IF NOT EXISTS user_orders (
    id INT PRIMARY KEY,
    user_id INT,
    status INT,
    order_amount DECIMAL(10,2),
    create_time DATETIME
);

-- define insert_data_to_table referring to @shao-ssq or @Spock12138
-- xxx
```

init videx env:

```sh
cd src/sub_platforms/sql_opt/videx/scripts
mysql -h{videx_host} -P13308 -uvidex -ppassword < setup_mysql57_env.sql
```

insert data, build env and explain sql step by step:
```sh

# step 1
# insert data into MySQL 5.7
CALL insert_data_to_table('user_orders', 1, 100000);
# build env
python videx_build_env.py --target {target_host}:{port}:test_cost_db:{user}:{pwd} --videx {videx_host}:13308:videx_test_cost_db:videx:password
# explain on both MySQL5.7 and VIDEX
EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_100k WHERE status = 1\G

# step 2
# insert data into MySQL 5.7
CALL insert_data_to_table('user_orders', 100001, 100000);
# build env
python videx_build_env.py --target {target_host}:{port}:test_cost_db:{user}:{pwd} --videx {videx_host}:13308:videx_test_cost_db:videx:password
# explain on both MySQL5.7 and VIDEX
EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_100k WHERE status = 1\G


# step 3
# insert data into MySQL 5.7
CALL insert_data_to_table('user_orders', 200001, 100000);
# build env
python videx_build_env.py --target {target_host}:{port}:test_cost_db:{user}:{pwd} --videx {videx_host}:13308:videx_test_cost_db:videx:password
# explain on both MySQL5.7 and VIDEX
EXPLAIN FORMAT = JSON SELECT id, user_id, order_amount FROM user_orders_100k WHERE status = 1\G


```

**Comment by kr11** [comment]
@shao-ssq @Spock12138  
PR #22 has identified the cause: `model_cache` is not being cleared, and the metadata file is being reused.

To obtain the correct result in the current version (with the bug), execute the following commands before running `videx_build_env.py`:

```bash
# Remove the cached metadata file.
rm videx_metadata_test_cost_db.json 

# Clear all cache on the VIDEX server.
curl http://{videx_host}:5001/clear_cache

**Comment by shao-ssq** [comment]
You're right that there is no discrepancy in the absence of indexes. However, discrepancies between the estimated and actual values still occur when indexes are present in the table.

**Comment by kr11** [comment]
> You're right that there is no discrepancy in the absence of indexes. However, discrepancies between the estimated and actual values still occur when indexes are present in the table.

That's an insightful discovery. I've added an index and reproduced your deviation. It seems to be a bug in MySQL's InnoDB. MySQL sometimes significantly deviates (about 2x) when estimating cardinality (records_in_range) using InnoDB. In fact, Videx provides a more accurate estimate.

Let's consider the following example: the actual row count is approximately 33,497, Videx estimates 33,517 (with a deviation of < 0.05%), whereas InnoDB's estimate is 50,031.

![Image](https://github.com/user-attachments/assets/aa16607f-2dab-4430-b911-5b3ec7bf35e2)

**Comment by shao-ssq** [comment]
Thank you for your efforts. It seems that this issue cannot be fully resolved for now, but as far as I'm concerned, the part related to index fluctuation is already sufficient for my needs.
